config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # For user authentication
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  # Defines the root path route ("/")
  root "dashboard#index"

  resources :projects
  resources :task_logs, path: "logs" do
    collection do
      post :index
      post :new_entry, action: :create
    end
  end
  resources :time_logs, path: "time-logs", only: [ :create, :destroy, :update ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pagy::Backend

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [ :firstname, :lastname, :profile_image ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/application/_flash_message.html.erb
<% if flash[:notice] %>
  <div role="alert" class="flash alert alert-success">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-6 w-6 shrink-0 stroke-current"
      fill="none"
      viewBox="0 0 24 24">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
    <span><%= notice %></span>
  </div>
<% end %>
<% if flash[:error] %>
  <div role="alert" class="flash alert alert-error">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-6 w-6 shrink-0 stroke-current"
      fill="none"
      viewBox="0 0 24 24">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
    <span><%= alert %></span>
  </div>
<% end %>

app/views/application/_sidebar.html.erb
<div class="sidebar-container h-full w-full relative" data-controller="sidebar">
  <div class="user-info-wrapper relative flex items-center justify-start gap-2 px-5 py-3">
    <% if current_user.profile_image.attached? %>
      <%= image_tag current_user.profile_image, class: "avatar size-10 rounded shadow-md", alt: "User Profile Image" %>
    <% else %>
      <img src="https://placehold.jp/40x40.png" class="avatar size-10 rounded shadow-md" alt="Project Placeholder" />
    <% end %>
    <div class="name-wrapper string grow ">
      <p class="font-semibold text-sm"><%= current_user.fullname %></p>
      <p class="text-xs text-neutral-content"><%= current_user.email %></p>
    </div>
    <div class="collapse-button btn btn-square btn-primary btn-xs absolute -right-3 -bottom-3 rounded shadow" data-action="click->sidebar#toggleSideNav">
      <i class="fa-solid fa-chevron-left"></i>
    </div>
  </div>
  <div class="menu-container px-5 py-3">
    <p class="ml-2 text-neutral string">Timer</p>
    <%= link_to task_logs_path, class: "menu-option" do %>
      <i class="fa-regular fa-clock"></i>
      <p class="font-semibold string ">Timer</p>
    <% end %>
    <div class="divider my-1"></div>
    <p class="ml-2 text-neutral string">Analyze</p>
    <button class="menu-option">
      <i class="fa-solid fa-chart-column"></i>
      <p class="font-semibold string">Reports</p>
    </button>
    <button class="menu-option">
      <i class="fa-solid fa-chart-pie"></i>
      <p class="font-semibold string">Analytics</p>
    </button>
    <button class="menu-option">
      <i class="fa-solid fa-rocket"></i>
      <p class="font-semibold string">Insights</p>
    </button>
    <div class="divider my-1"></div>
    <p class="ml-2 text-neutral string">Management</p>
    <%= link_to projects_path, class: "menu-option" do %>
      <i class="fa-solid fa-chart-column"></i>
      <p class="font-semibold string">Projects</p>
    <% end %>
    <button class="menu-option">
      <i class="fa-solid fa-chart-pie"></i>
      <p class="font-semibold string">Teams</p>
    </button>
    <button class="menu-option">
      <i class="fa-solid fa-rocket"></i>
      <p class="font-semibold string">Invoices</p>
    </button>
  </div>
  <div class="extra-options-container w-full absolute bottom-0 px-5 py-3">
    <%= link_to edit_user_registration_path, class: "menu-option" do %>
      <i class="fa-solid fa-gear"></i>
      <p class="font-semibold string">Settings</p>
    <% end %>
    <%= link_to destroy_user_session_path, data: { turbo_method: :delete },  class: "menu-option" do %>
      <i class="fa-solid fa-right-from-bracket"></i>
      <p class="font-semibold string">Logout</p>
    <% end %>
  </div>
</div>