config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # For user authentication
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  # Defines the root path route ("/")
  root "dashboard#index"

  resources :projects
  resources :task_logs, path: "logs" do
    collection do
      post :index
      post :new_entry, action: :create
    end
  end
  resources :time_logs, path: "time-logs", only: [ :create, :destroy, :update ]
end

app/controllers/task_logs_controller.rb
class TaskLogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [ :update ]
  def index
    @active_task = current_user.time_logs.where(status: :ongoing).last
    @pagy, @task_logs = pagy(current_user.time_logs.where(status: :done).order(created_at: :desc), limit: 5)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def create
    task = current_user.tasks.new(task_params)

    respond_to do |format|
      Task.transaction do
        if task.save && task.time_logs.build(start_time: DateTime.now, status: :ongoing, user: current_user).save
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(
              "task_frame",
              partial: "active_task",
              locals: { task: task }
            )
          end
          format.html { redirect_to task_logs_path, notice: "Task created successfully." }
        else
          format.html { redirect_to task_logs_path, alert: "Failed to create task.", status: :unprocessable_entity }
          raise ActiveRecord::Rollback
        end
      end
    rescue ActiveRecord::RecordInvalid => e
      format.html { redirect_to task_logs_path, alert: "An error occurred: #{e.message}", status: :unprocessable_entity }
    end
  end


  def update
    time_log = @task.active_time_log
    if params[:stop]
      time_log.update(end_date: DateTime.now, status: :done)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("task_frame", partial: "form"),
            turbo_stream.prepend("tasks_logs", partial: "task", locals: { time_log: time_log })
          ]
        end
      end
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :project_id)
  end

  def set_task
    @task = Task.find(params[:id])

    redirect_to task_logs_path, notice: "Task not found." unless @task
  end
end

app/helpers/task_logs_helper.rb
module TaskLogsHelper
  def time_spent(start_time, end_date)
    return "N/A" if start_time.nil? || end_date.nil?

    total_seconds = (end_date - start_time).to_i
    hours = total_seconds / 3600
    minutes = (total_seconds % 3600) / 60
    seconds = total_seconds % 60

    format("%02d:%02d:%02d", hours, minutes, seconds)
  end
end

app/views/task_logs/_active_task.html.erb
<turbo-frame id="task_frame">
  <div class="container bg-base-300 px-5 py-4 rounded-md" data-controller="timer" data-timer-start-time-value="<%= task.active_time_log.start_time %>">
    <div class="w-full flex max-[1040px]:flex-col items-center justify-between">
      <p class="text-lg max-[1040px]:w-full"><%= task.name %></p>
      <div class="divider min-[1041px]:hidden"></div>
      <div class="flex items-center max-[1040px]:justify-between max-[1040px]:w-full min-[1041px]:max-w-max">
        <p class="text-sm min-[1041px]:mx-5 text-primary">📂 <%= task.project.name %></p>
        <div class="flex items-center max-w-max">
          <div id="task-timer" class="text-lg font-semibold mr-5" data-timer-target="timer">
            00:00:00
          </div>
          <%= link_to "Stop Timer", task_log_path(task, stop: true), data: { turbo_method: :patch }, class: "btn btn-error" %>
        </div>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/task_logs/_edit_modal.html.erb
<dialog id="timeLogModal<%= time_log.id %>" class="modal">
  <div class="modal-box">
    <form method="dialog">
      <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
    </form>
    <h3 class="text-lg font-bold">Edit Task Log</h3>
    <%= form_with(model: time_log, class: "w-full mt-5") do |f| %>
      <%= f.fields_for :task do |task| %>
        <div class="field w-full px-0 mt-2">
          <%= task.label :name %>
          <%= task.text_field :name, value: time_log.task.name, class: "input input-bordered w-full" %>
        </div>
        <div class="field w-full px-0 mt-2">
          <%= task.label :project_id %>
          <%= task.select :project_id, Project.all.collect { |p| [p.name, p.id] }, { prompt: 'Select a project', selected: time_log.task&.project_id }, class: "select select-bordered w-full" %>
        </div>
      <% end %>
      <div class="field w-full px-0 mt-2">
        <%= f.label :start_time, "Start" %>
        <%= f.datetime_field :start_time, class: "input input-bordered w-full" %>
      </div>
      <div class="field w-full px-0 mt-2">
        <%= f.label :end_date, "End" %>
        <%= f.datetime_field :end_date, class: "input input-bordered w-full" %>
      </div>
      <div class="action text-sm mt-2">
        <%= f.submit "Save", class: "btn btn-primary float-right" %>
      </div>
    <% end %>
  </div>
</dialog>

app/views/task_logs/_form.html.erb
<turbo-frame id="task_frame">
  <div class="container bg-base-300 px-5 py-4 rounded-md">
    <%= form_with model: Task.new, url: new_entry_task_logs_path, class: "w-full flex flex items-center max-[1040px]:flex-col items-center justify-between" do |f| %>
      <%= f.text_field :name, class: "input input-bordered flex items-center w-full max-w-full input-md", autofocus: true, autocomplete: "name", placeholder: "What are you working on?", required: true %>
      <div class="divider min-[1041px]:hidden"></div>
      <div class="flex items-center justify-center max-[1040px]:justify-between max-[1040px]:w-full">
        <%= f.select :project_id, Project.all.collect { |p| [p.name, p.id] }, { prompt: 'Select a project' }, class: "select select-bordered max-[1040px]:w-full min-[1041px]:max-w-xs min-[1041px]:ms-4" %>
        <div id="task-timer" class="text-lg font-semibold mx-5">
          00:00:00
        </div>
        <%= f.submit "Start Time", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</turbo-frame>

app/views/task_logs/_task.html.erb
<%= turbo_frame_tag dom_id(time_log) do %>
  <div class="container bg-base-300 px-5 py-4 my-5 rounded-md" >
    <div class="w-full flex max-[1040px]:flex-col items-center justify-between">
      <div class="flex items-center max-[1040px]:justify-between max-[1040px]:w-full min-[1041px]:max-w-1/2">
        <p class="text-md truncate"><%= time_log.task.name %></p>
        <p class="text-sm ms-5 text-primary truncate">📂 <%= time_log.task.project.name %></p>
      </div>
      <div class="divider min-[1041px]:hidden"></div>
      <div class="flex items-center max-[1040px]:justify-around max-[1040px]:w-full min-[1041px]:max-w-max">
        <div class="divider divider-horizontal max-[1040px]:hidden"></div>
        <p class="text-sm text-wrap"><%= time_log.start_time.strftime("%H:%M") %> - <%= time_log.end_date.strftime("%H:%M") %></p>
        <div class="divider divider-horizontal"></div>
        <p class="text-sm"><%= time_spent(time_log.start_time, time_log.end_date) %></p>
        <div class="divider divider-horizontal"></div>
        <%= link_to time_logs_path(task_id: time_log.task_id), data: { turbo_method: :post }, class: "btn btn-ghost max-[1040px]:px-10" do %>
          <i class="fa-solid fa-play"></i>
        <% end %>
        <div class="divider divider-horizontal min-[1041px]:hidden"></div>
        <div class="dropdown dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost max-[1040px]:px-10">
            <i class="fa-solid fa-ellipsis-vertical"></i>
          </div>
          <ul tabindex="0" class="dropdown-content menu bg-base-100 rounded-box z-[1] w-52 p-2 shadow">
            <li>
              <a onclick="timeLogModal<%= time_log.id %>.showModal()">Update</a>
            </li>
            <li>
              <%= link_to "Delete", time_log, method: :delete, data: { turbo_method: :delete } %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: "task_logs/edit_modal", locals: { time_log: time_log }%>
<% end %>

app/views/task_logs/_task_list.html.erb
<% task_logs.each do | log | %>
  <%= render partial: 'task', locals: {time_log: log }%>
<% end %>

app/views/task_logs/index.html.erb
<div class="main-container">
  <div class="flex items-center justify-between mb-10">
    <h1 class="text-xl font-bold">Task Logs ⏱️</h1>
  </div>
  <% if @active_task.present? %>
    <%= render partial: 'active_task', locals: {task: @active_task.task }%>
  <% else %>
    <%= render partial: 'form' %>
  <% end %>
  <div class="divider my-10">Recent Task Logs</div>
  <%= turbo_frame_tag "tasks_logs" do %>
    <%= render partial: "task_list", locals: { task_logs: @task_logs } %>
  <% end %>
  <div id="load_more_button" class="w-full flex justify-center">
    <%= button_to "Load More", pagy_url_for(@pagy, @pagy.next), data: { turbo_method: :post }, class: "btn btn-primary"%>
  </div>
</div>

app/views/task_logs/index.turbo_stream.erb
<%= turbo_stream.append "tasks_logs" do %>
  <%= render partial: "task_logs/task_list", locals: { task_logs: @task_logs } %>
<% end %>
<%= turbo_stream.update "load_more_button" do %>
  <% unless @pagy.next.nil? %>
    <%= button_to "Load More", pagy_url_for(@pagy, @pagy.next), data: { turbo_method: :post }, class: "btn btn-primary"%>
  <% end %>
<% end %>